runtime: php55
api_version: 1

handlers:
- url: /
  script: home.php

- url: /index\.html
  script: home.php

- url: /blog\.html
  script: blog.php

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /contact\.html
  script: contact.php
  
- url: /resume\.html
  script: resume.php
  
- url: /project\.html
  script: project.php

- url: /.*
  script: error404.php
