runtime: php55
api_version: 1

handlers:
- url: /
  script: home.php

- url: /favicon\.ico
  upload: favicon.ico
  static_files: favicon.ico

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /index
  script: home.php

- url: /blog
  script: blog.php

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /contact
  script: contact.php

- url: /resume
  script: resume.php

- url: /project
  script: project.php

- url: /experiment
  script: experiment.php

- url: /.*
  script: error404.php
