runtime: php55
api_version: 1

handlers:

- url: /stylesheet
  static_dir: stylesheet

- url: /fonts.css
  script: fonts.css
  
- url: /
  script: home.php

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /jsgame
  static_dir: jsgame

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: error404.php